# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo/todo.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("todo/todo.proto", :syntax => :proto3) do
    add_message "todo.Task" do
      optional :text, :string, 1
      optional :done, :bool, 2
    end
    add_message "todo.TaskList" do
      repeated :tasks, :message, 1, "todo.Task"
    end
    add_message "todo.Text" do
      optional :text, :string, 1
    end
    add_message "todo.Void" do
    end
  end
end

module Todo
  Task = Google::Protobuf::DescriptorPool.generated_pool.lookup("todo.Task").msgclass
  TaskList = Google::Protobuf::DescriptorPool.generated_pool.lookup("todo.TaskList").msgclass
  Text = Google::Protobuf::DescriptorPool.generated_pool.lookup("todo.Text").msgclass
  Void = Google::Protobuf::DescriptorPool.generated_pool.lookup("todo.Void").msgclass
end
